FROM osgeo/gdal:ubuntu-small-3.2.1

ARG requirements_file

COPY ./$requirements_file ./requirements.txt

RUN apt-get -qqy update \
  && apt-get install -y lsb-release wget gnupg2 libpq-dev && apt-get clean all \
  && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' \
  && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
  && apt-get -qqy update \
# Install the latest version of PostgreSQL.
# If you want a specific version, use 'postgresql-12' or similar instead of 'postgresql':
  && apt-get -y install postgresql \
  && curl -sSL https://sdk.cloud.google.com | bash \
  && curl -sL https://aka.ms/InstallAzureCLIDeb | bash \
  && apt-get install -qqy python3-pip libspatialindex-dev git \
  && python3 -m pip install -r requirements.txt

ENV PATH $PATH:/root/google-cloud-sdk/bin
