FROM mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04

ARG requirements_file

COPY ./$requirements_file ./requirements.txt

RUN apt-get -qqy update \
  && apt-get install -qqy python3-pip libspatialindex-dev git libgeos-dev python-numpy cython cython3 \
  && python3 -m pip install -r requirements.txt

RUN pip install horovod

CMD /bin/bash
