epochs: 48
cv_samples: 5120
test_samples: 512
learning_rate: 0.025
learning_schedule_gamma: 0.99
loss_function: nn.MSELoss
seed: 1337
batch_size: 8
num_workers: 6
label_file: '/vsiaz/hls/hag_suraci/hag_suraci_2016.vrt'
chipper: hm_chipper
use_hvd: false
num_gpus: 6
