epochs: 250
training_samples: 2500
test_samples: 1000
#training_samples: 50
#test_samples: 10
learning_rate: 0.025
learning_schedule_gamma: 0.99
loss_function: nn.MSELoss
seed: 1337
training_aoi_file: 'urban_training_areas.gpkg'
test_aoi_file: 'conus.geojson'
batch_size: 8
num_workers: 6
label_file: '/vsiaz/hls/hm_fixed/HM_ee_2017_v014_500_30.vrt'
chipper: hm_chipper
use_hvd: true
num_gpus: 20
label_bands: [5]
