epochs: 48
cv_samples: 5120
test_samples: 512
learning_rate: 0.025
learning_schedule_gamma: 0.99
loss_function: nn.MSELoss
seed: 13373
batch_size: 8
num_workers: 6
label_file: '/vsiaz/hls/hurban/Hurban_2017v012c_30_75th.vrt'
training_file: '/vsiaz/hls/conus_hls_median_viirs_2013.vrt'
chipper: hm_chipper
use_hvd: false
num_gpus: 6
