epochs: 100
training_samples: 2500
test_samples: 1000
learning_rate: 0.02
learning_schedule_gamma: 0.99
seed: 1337
training_aoi_file: 'urban_training_areas.gpkg'
test_aoi_file: 'conus.geojson'
batch_size: 1
label_file: '/vsiaz/hls/hm_fixed/HM_ee_2017_v014_500_30.vrt'
chipper: hm_chipper
