epochs: 250
training_samples: 2500
test_samples: 1000
#training_samples: 50
#test_samples: 10
learning_rate: 0.025
learning_schedule_gamma: 0.99
loss_function: nn.MSELoss
seed: 13373
training_aoi_file: 'hurban_training_areas.gpkg'
#training_aoi_file: 'conus.geojson'
test_aoi_file: 'conus.geojson'
batch_size: 8
num_workers: 6
label_file: '/vsiaz/hls/hurban/Hurban_2017v012c_30_75th.vrt'
training_file: 'model/data/azml/conus_hls_median_2013.vrt'
chipper: hm_chipper
use_hvd: true
num_gpus: 20
