epochs: 100
training_samples: 2500
validation_samples: 1000
test_samples: 1000
learning_rate: 0.01
learning_schedule_gamma: 0.95
loss_function: nn.MSELoss
seed: 1337
batch_size: 8
num_workers: 6
label_file: '/vsiaz/hls/hm_fixed/HM_ee_2017_v014_500_30.vrt'
chipper: hm_chipper
use_hvd: true
num_gpus: 20
label_bands: [4]
